### ISSUE TITLE
Query queue doesnt show if its permanent or temporary

### ISSUE THREAD

**Issue by lechen26** [shyifrah/kas#34]
if we can define queue to be permanent or temporary, and also alter it afterwards, this property should be seen while viewing all information regarding the queue.
q q queue1 all doesnt show this information.

**Comment by shyifrah** [comment]
A value of "true" in the "backup" attribute (see below) means that a queue is permanent, while a value of "false" means it is temporary.

```
KAS/MQ Admin> q q * all
Queue.............: ALPHAQ1
  Owned by...: alpha
  Accessed...: By system at 2018-12-12 19:07:08,960 for method expire()
  Threshold..: 1000
  Backup.....: true
  Messages...: 0

```

closes #34
